### ISSUE TITLE
What is the unit of "startTime" and "duration" properties?

### ISSUE THREAD

**Issue by mantaroh** [seanyhlin/TV-Manager-API#3]
Hi all.

TVPorgram has "startTime" and "duration" property.
But it is not specified unit.

According to [1] sites, EIT's duration unit is second.
Is this document's unit  millis or sec?

Additionally,  Date object which specified by ECMA is based on millis.
If TVProgram's property is seconds, Web Apps should convert seconds to millis.

[1] http://epg.cherryhill.eu/what
[2] http://www.ecma-international.org/ecma-262/5.1/#sec-15.9

**Comment by seanyhlin** [comment]
Hi Mantaroh,

We expect "startTime" and "duration" in millis. I'll clarify this part in the spec to prevent future confusion.

Thank you.
